author: "Badlop <badlop at process-one.net>"
category: "captcha"
summary: "Generate CAPTCHAs using Rust library"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
