author: "Badlop <badlop at process-one.net>"
category: "admin"
summary: "Additional ejabberd commands"
home: "https://github.com/processone/mod_admin_extra"
url: "git@github.com:processone/mod_admin_extra.git"
