author: "Lavrin"
category: "admin"
summary: "Easy tracing of connections made to ejabberd"
home: "https://github.com/lavrin/ejabberd-trace/tree/master/"
url: "git@github.com:lavrin/ejabberd-trace.git"
