author: "Mark.Wang Wxj3791906@gmail.com"
category: "monitor"
summary: "Provides access to get ejabberd runtime info interface"
home: "https://github.com/lemon2015/ejabberd-prometheus-exporter"
url: "https://github.com/lemon2015/ejabberd-prometheus-exporter.git"
