author: "Badlop <badlop at process-one.net>"
category: "web"
summary: "Show webchat_url in MUC rooms disco#info"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
