author: "Tim Stewart <tim at stoo.org>"
category: "log"
summary: "Logs messages to an HTTP API"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
