author: "Holger Weiss <holger at zedat.fu-berlin.de>"
category: "log"
summary: "Log one line per message transmission in text file"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
