author: "Holger Weiss <holger at zedat.fu-berlin.de>"
category: "policy"
summary: "Prevent OMEMO sessions from being established"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
