author: "Pouriya Jahanbakhsh <pouriya.jahanbakhsh@gmail.com>"
category: "stats"
summary: "Prometheus metrics"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
