author: "Badlop <badlop at process-one.net>"
category: "stats"
summary: "Observer CLI plugins for ejabberd"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
