listen:
  -
    port: 5289
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /metrics: mod_prometheus

modules:
  mod_prometheus:
    mnesia: true
    vm:
      memory: true
      system_info: true
      statistics: false
      distribution: false
      microstate_accounting: false
    hooks:
      # Histogram for a hook:
      - hook: user_send_packet
        type: histogram
        help: "Handling of sent messages duration in millisecond"
        labels:
          - host
          - stanza
      # Histogram for all modules of a hook:
      - hook: user_receive_packet
        type: histogram
        help: "Handling of received messages duration in millisecond"
        labels:
          - host
          - stanza
          - module
      # Counter for a hook:
      - hook: sm_register_connection_hook
        type: counter
        labels:
          - host
          - stanza
      # Counter for all modules of a hook:
      - hook: sm_remove_connection_hook
        type: counter
        labels:
          - host
          - stanza
          - module
        help: "Number of closed c2s sessions"
      # Histogram for some modules (callbacks) of a hook:
      - hook: user_send_packet
        type: histogram
        labels:
          - host
        collect:
          - module: mod_carboncopy
            function: user_send_packet
            help: "Handling of carbon copied messages in millisecond"
          - module: mod_mam
            function: user_send_packet
            help: "Handling of MAM messages in millisecond"
            labels:
              # It also inherits above `host` label
              - stanza
            buckets:
              - 10
              - 100
              - 750
              - 1000
              - 1500
