author: "Magnus Henoch <henoch at dtek.chalmers.se>"
category: "data"
summary: "User Profile (XEP-0154) in Mnesia table"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
