{'../ejabberd-dev/src/gen_mod', [{outdir, "../ejabberd-dev/ebin"},{i,"../ejabberd-dev/include"}]}.
{'src/mod_statsdx',     [{outdir, "ebin"},{i,"../ejabberd-dev/include"}]}.
{'src/mod_stats2file',     [{outdir, "ebin"},{i,"../ejabberd-dev/include"}]}.
