author: "Badlop <badlop at process-one.net>"
category: "purge"
summary: "Keep graveyard of accounts and rooms tombstones"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
