{"Your Jabber account was succesfully created.", "Ваш Jabber-аккаунт был успешно создан."}.
{"There was an error creating the account: ", "Ошибка при создании аккаунта:"}.
{"Your Jabber account was succesfully deleted.", "Ваш Jabber-аккаунт был успешно удален."}.
{"There was an error deleting the account: ", "Ошибка при удалении аккаунта:"}.
{"The password of your Jabber account was succesfully changed.", "Пароль Вашего Jabber-аккаунта был успешно изменен."}.
{"There was an error changing the password: ", "Ошибка при смене пароля:"}.
{"Jabber Account Registration", "Регистрация Jabber-аккаунта"}.
{"Register a Jabber account", "Зарегистрировать Jabber-аккаунт"}.
{"Unregister a Jabber account", "Удалить Jabber-аккаунт"}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.", "Здесь Вы можете создать Jabber-аккаунт на этом Jabber-сервере. Ваш JID (Jabber-идентификатор) будет в виде: \"пользователь@сервер\". Пожалуйста, внимательно читайте инструкции для правильного заполнения полей."}.
{"Username:", "Имя пользователя:"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.", "Регистр не имеет значения: \"маша\" и \"МАША\" будет считаться одним и тем же именем."}.
{"Characters not allowed: @ : ' \" < > &", "Недопустимые символы: @ : ' \" < > &"}.
{"Server:", "Сервер:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.", "Не говорите никому свой пароль, даже администраторам сервера."}.
{"You can later change your password using a Jabber client.", "Позже Вы можете изменить пароль через Jabber-клиент."}.
{"Some Jabber clients can store your password in your computer. Use that feature only if you trust your computer is safe.", "Некоторые Jabber-клиенты могут сохранять пароль на Вашем компьютере. Используйте эту функцию только в том случае, если считаете это безопасным."}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.", "Запомните пароль или запишите его на бумаге, которую сохраните в безопасном месте. В Jabber'е нет автоматизированного средства восстановления пароля в том случае, если Вы его забудете."}.
{"Password Verification:", "Проверка пароля:"}.
{"Register", "Зарегистрироваться"}.
{"Old Password:", "Старый пароль:"}.
{"New Password:", "Новый пароль:"}.
{"This page allows to unregister a Jabber account in this Jabber server.", "Здесь Вы можете удалить Jabber-аккаунт с этого сервера."}.
{"Unregister", "Удалить"}.
