{"Your Jabber account was succesfully created.", "Ваш Jabber-акаунт було успішно створено."}.
{"There was an error creating the account: ", "Помилка при створенні акаунту:"}.
{"Your Jabber account was succesfully deleted.", "Ваш Jabber-акаунт було успішно видалено."}.
{"There was an error deleting the account: ", "Помилка при видаленні акаунту: "}.
{"The password of your Jabber account was succesfully changed.", "Пароль вашого Jabber-акаунту був успішно змінений."}.
{"There was an error changing the password: ", "Помилка при зміні пароля: "}.
{"Jabber Account Registration", "Реєстрація Jabber-акаунту"}.
{"Register a Jabber account", "Зареєструвати Jabber-акаунт"}.
{"Unregister a Jabber account", "Видалити Jabber-акаунт"}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.", "Тут ви можете зареєструвати обліковий запис Jabber на цьому сервері. Ваш JID (ідентифікатор Jabber) матиме вигляд \"користувач@сервер\". Щоб вірно заповнити поля нижче, будь ласка, уважно читайте інструкції до них."}.
{"Username:", "Ім'я користувача:"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.", "Регістр не має значення: \"МАША\" та \"маша\" буде сприйматися як одне й те саме ім'я."}.
{"Characters not allowed: @ : ' \" < > &", "Заборонені символи: @ : ' \" < > &"}.
{"Server:", "Сервер:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.", "Нікому не кажіть свій пароль, навіть адміністраторам сервера."}.
{"You can later change your password using a Jabber client.", "Пізніше можна змінити пароль через Jabber-клієнт."}.
{"Some Jabber clients can store your password in your computer. Use that feature only if you trust your computer is safe.", "Деякі Jabber-клієнти можуть зберігати пароль на вашому комп'ютері. Користуйтесь цією функцією тільки у тому випадку, якщо вважаєте її безпечною."}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.", "Запам'ятайте пароль, або запишіть його на папері, який треба зберегти у безпечному місці. У Jabber'і немає автоматизованих засобів відновлення пароля на той випадок, якщо ви його забудете."}.
{"Password Verification:", "Перевірка пароля:"}.
{"Register", "Зареєструвати"}.
{"Old Password:", "Старий пароль:"}.
{"New Password:", "Новий пароль:"}.
{"This page allows to unregister a Jabber account in this Jabber server.", "Тут ви можете видалити свій акаунт з цього Jabber-сервера."}.
{"Unregister", "Видалити"}.
