author: "Guus der Kinderen <guus.der.kinderen@gmail.com>"
category: "stats"
summary: "Exposes server information over Pub/Sub"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"
